version: '3.8'

services:
  mendel-challenge-backend:
    container_name: mendel-challenge-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - mendel-network
    restart: unless-stopped

networks:
  mendel-network:
    driver: bridge
